
export const ADD_TO_CART = 'ADD_TO_CART' 
 export const DELECT_FROM_CART = 'DELECT_FROM_CART' 
 export const SET_CHECKOUT_STATUS = 'SET_CHECKOUT_STATUS' 
 export const RECEIVE_PRODUCTS = 'RECEIVE_PRODUCTS' 
export const GET_PRODUCTS = 'GET_PRODUCTS'
